from typing import Literal
from typing_extensions import Self

from dolfinx.fem import Function
from dolfinx.mesh import Mesh
from matplotlib.collections import PolyCollection
import numpy as np

from ..utils.fenicsx_utils import (
    dofs, CellType, mesh_vertices, mesh_coordinates, mesh_axes, is_simplicial,
    is_scalar, NonScalarError,
)
from ..utils.py_utils import optional_lru_cache


class QuadMesh:
    def __init__(
        self, 
        x_coordinates, 
        y_coordinates, 
        quads,
        name: str | None = None,
    ):
        ...

    @classmethod
    def from_mesh(
        cls: type['QuadMesh'], 
        mesh: Mesh,
    ) -> Self:
        ...



@optional_lru_cache
def quad_mesh(
    mesh: Mesh,
    **polycollection_kwargs,
) -> PolyCollection:
    if not mesh.geometry.dim == 2:
        raise ValueError(
            f"""
        Quadrangulation only valid in 2D, not 
        dimension {mesh.geometry.dim} """
        )

    if is_simplicial(mesh):
        raise ValueError(
            f""" 
        Quadrangulation only valid with quadrilateral cells, not 
        {mesh.topology.cell_name()} """
        )

    xy_coordinates = mesh.geometry.x[:, :2]

    connec = mesh.topology.connectivity(mesh.geometry.dim, 0)
    n_cells = connec.num_nodes
    quads = [_reorder_quad_vertices(connec.links(i)) for i in range(n_cells)]

    vertices = xy_coordinates[quads]

    _kwargs = dict(facecolor='white', edgecolor='black')
    _kwargs.update(polycollection_kwargs)
    quadl = PolyCollection(vertices, **_kwargs)

    return quadl




def _reorder_quad_vertices(
    cell_vertices: np.ndarray,
    initial_ordering: Literal["N", "Z"] = "N",
    final_ordering: Literal["clockwise", "anticlockwise"] = "clockwise",
) -> np.ndarray:
    """
    Quadrilateral meshes generated by `dolfinx` have a local
    indexing of cell vertices that is self-intersecting 
    (e.g. forming an N-shape or Z-shape)

    ```
    1 _______ 3
    |         |
    |         |
    0 ‾‾‾‾‾‾‾ 2
    ```

    A `matplotlib` quadrangulation requires local indexing
    of cell vertices to be non-self-intersecting (i.e. clockwise
    or anticlockwise)

    ```
    1 _______ 2
    |         |
    |         |
    0 ‾‾‾‾‾‾‾ 3
    ```

    """
    assert len(cell_vertices) == 4

    if initial_ordering == 'N':
        if final_ordering == "clockwise":
            initial_final_map = {
                0: 0, 
                1: 1,
                2: 3,
                3: 2,
            }
        elif final_ordering == "anticlockwise":
            initial_final_map = {
                0: 0, 
                1: 2,
                2: 3,
                3: 1,
            }
        else:
            raise ValueError(f'{final_ordering} not recognised')
        
    elif initial_ordering == 'Z':
        raise NotImplementedError
    
    else:
        raise ValueError(f'{initial_ordering} not recognised')
    
    reordered = np.zeros(len(cell_vertices), dtype=np.int32)
    for initial, final in initial_final_map.items():
        reordered[initial] = cell_vertices[final]
    
    return reordered


