from .ufl_utils import (
    is_scalar, 
    is_vector, is_tensor, extract_mesh, extract_meshes,
    is_shape, 
    is_continuous_lagrange, is_discontinuous_lagrange, 
    is_same_element, is_family_alias, extract_integrands,
    extract_integrand,
    VectorError,
    ScalarError,
    ScalarVectorError,
    ShapeError,
    is_zero,
    extract_function_space,
)
from .dofs_utils import (
    SpatialMarkerAlias,
    SpatialMarker, 
    dofs_indices,
    dofs,
    as_spatial_marker,
    limits_corrector,
    DofsMethodType,
    FacetMethodType,
)
from .mesh_utils import(
    CellType,
    DiagonalType,
    BoundaryType,
    create_tagged_measure, 
    mesh_integral,
    mesh_axes,
    mesh_vertices_tensor,
    mesh_vertices,
    mesh_coordinates,
    mesh_axes_spacing,
    cell_sizes,
    cell_size_quantity,
    cell_aspect_ratios,
    number_of_cells,
    number_of_entities,
    is_cartesian,
    is_uniform_cartesian,
    is_simplicial,
    NonCartesianQuadMeshError,
    NonCartesianMeshError,
)
from .fem_utils import (
    create_constant, 
    create_function, 
    create_function_space, 
    get_component_functions,
    set_fem_constant, 
    set_fem_function, 
    set_fem_function_interpolate,
    is_mixed_space,
    get_fem_subspace,
    get_fem_subspaces,
)